name: auto_divider
description: Flutter widgets for easily adding gaps or dividers inside Flex widgets such as Columns and Rows or scrolling views.
version: 1.1.0
homepage: https://github.com/sososdk/gap

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

